openapi: 3.0.3
info:
  title: Simplified login API specification
  description: |-
    This OpenAPI document describes the simplified login API.
    Copy and paste the API from the `paths` key to your OpenAPI document.
  version: "1"


paths: 

  
  /session/{username}:
    parameters:
      - name: username
        schema: {$ref: "#/components/schemas/Username"}
        in: path
        required: true
        description: Username

    get: 
      summary: user searched by its username
      operationId: getUserProfile
      description: |
        Obtains an user by its username. It returns a list with the attributes of the user, or "Error" if not found.
        
      responses:
        "200": {$ref: "#/components/responses/UserInfo" }
        "400": { $ref: "#/components/responses/BadRequest" }
        "404": { description: User not found}
        "500": { $ref: "#/components/responses/InternalServerError" }


  /session/{username}/stream:
    get: 
      parameters:
      - name: username
        schema: {$ref: "#/components/schemas/Username"}
        in: path
        required: true
        description: Username
      
      
      summary: Stream of photos of a user
      operationId: getMyStream
      description: |
        Obtains the stream of photos of a user searched by its username. It returns a list with all the photos in inverse chronological order
        
      responses:
        "200": { $ref: "#/components/responses/UserInfo" }

        "400": { $ref: "#/components/responses/BadRequest" }
        "404": { description: User not found}
        "500": { $ref: "#/components/responses/InternalServerError" }

components:

  responses:
  
    UserInfo:
      description: Request accepted, user found
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
              
    BadRequest:
      description: |
        The request was not compliant with the documentation
        (eg. missing fields, etc).

    InternalServerError:
      description: |
        The server encountered an internal error.
        Further info in server logs.

  schemas:
    
    ObjectWithInt:
      type: object
      properties:
        identifier:    
          type: integer
          example: 1
          
    Username:
      type: string
      example: "Maria"
      readOnly: true
      minLength: 3
      maxLength: 16
    
    

      
      