openapi: 3.0.3
info:
  title: Simplified login API specification
  description: |-
    This OpenAPI document describes the simplified login API.
    Copy and paste the API from the `paths` key to your OpenAPI document.
  version: "1"


paths: 

  
  /session/{userId}:
    parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: userId

    get: 
      summary: user searched by its userId
      operationId: getUserProfile
      description: |
        Obtains an user by its userId. It returns a list with the attributes of the user, or "Error" if not found.
        
      responses:
        "200": { $ref: "#/components/responses/UserInfo" }
        "400": { $ref: "#/components/responses/BadRequest" }
        "404": { description: User not found}
        "500": { $ref: "#/components/responses/InternalServerError" }


  /session/{userId}/stream:
    get: 
      parameters:
      - name: userId
        schema: {$ref: "#/components/schemas/IntegerOK"}
        in: path
        required: true
        description: userId
      
      
      summary: Stream of photos of a user
      operationId: getStream
      description: |
        Obtains the stream of photos of a user searched by its userId. It returns a list with all the photos in inverse chronological order
        
      responses:
        "200": { $ref: "#/components/responses/UserInfo" }
        "400": { $ref: "#/components/responses/BadRequest" }
        '401': { $ref: "#/components/responses/Error" }
        "500": { $ref: "#/components/responses/InternalServerError" }


  /session/login:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
        
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Username"
        required: true


      responses:
        '201': { $ref: "#/components/responses/OK" }
        '401': { $ref: "#/components/responses/Error" }
                
  /session/{userId}/uploadPhoto:
    post:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: userId

    
      tags: ["uploadPhoto"]
      summary: Uploads a photo by the user
      description: |-
        Uploads a photo by the logged user and it appends to the beginning of the list
        
      operationId: uploadPhoto
      requestBody:
        description: User photo upload
        content:
          image/png:
            schema:
              type: string
              format: binary
        required: true


      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }



  /session/{userId}/commentPhoto/{photoId}:
    post:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: userId
        
      - name: photoId
        schema: 
          type: integer
        in: path
        required: true
        description: ID of the photo to be commented
        
        
      
      
      tags: ["commentPhoto"]
      summary: Comments a photo of a user
      description: |-
        The logged user comments a photo of another user. Each photo has a unique identifier, so we won't have to specify the user.
        
      operationId: commentPhoto
      requestBody:
        description: Comment to be added to the requested photo.
        content:
          
          text/plain:
            schema:
              type: string
              description: Photo comment.
              example: "Wow, such a nice picture!"
        required: true


      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }


  /session/{userId}/likePhoto/{photoId}:
    put:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: userId
        
      - name: photoId
        schema: 
          type: integer
        in: path
        required: true
        description: ID of the photo to be liked
        
        
      
      
      tags: ["likePhoto"]
      summary: Likes a photo of a user
      description: |-
        The logged user likes a photo of another user. Each photo has a unique identifier, so we won't have to specify the user.
        
      operationId: likePhoto
    

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }
                
                
  /session/{userId}/setUserName:
    put:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: userId
        
      - in: query
        name: newUsername
        schema: {$ref: "#/components/schemas/Username"}
        required: true
        description: new username
        
        
      
      
      tags: ["setMyUserName"]
      summary: Given the user ID, changes username of the user
      description: |-
        The logged user changes its username. It returns 0 if it has been correctly updated, or -1 if an error has occurred.
        
      operationId: setMyUserName
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }
                
                

  /session/{userId}/followUser/{userFollowed}:
    put:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: userId
        
      - name: userFollowed
        schema: 
          type: integer
        in: path
        required: true
        description: user to be followed

      
      tags: ["followUser"]
      summary: Given a user ID, the logged user follows it.
      description: |-
        The logged user follows the user identified by the parameter. It returns 0 if it has been correctly followed, or -1 if an error has occurred (already followed or not found).
        
      operationId: followUser
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }
                
  /session/{userId}/banUser/{userBanned}:
    put:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: user logged

      - name: userBanned
        schema: 
          type: integer
        in: path
        required: true
        description: user to be banned
        
      
      tags: ["banUser"]
      summary: Given a user ID, the logged user bans it.
      description: |-
        The logged user bans the user identified by the parameter. It returns 0 if it has been correctly banned, or -1 if an error has occurred (already banned or not found).
        
      operationId: banUser
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }
  
  /session/{userId}/unfollowUser/{unfollowedUserId}:
    delete:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: user logged
        
      - name: unfollowedUserId
        schema: 
          type: integer
        in: path 
        required: true
        description: user to be unfollowed

        
      
      
      tags: ["unfollowUser"]
      summary: Given a user ID, the logged user unfollows it.
      description: |-
        The logged user unfollows the user identified by the parameter. It returns 0 if it has been correctly unfollowed, or -1 if an error has occurred (previously not followed or not found).
        
      operationId: unfollowUser
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }


  /session/{userId}/unbanUser/{bannedUserId}:
    delete:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: user logged
        
      - name: bannedUserId
        schema: 
          type: integer
        in: path 
        required: true
        description: user to be unbanned

        
      
      
      tags: ["unbanUser"]
      summary: Given a user ID, the logged user unbans it (it deletes it from the list of banned users)
      description: |-
        The logged user unbans the user identified by the parameter. It returns 0 if it has been correctly unbanned, or -1 if an error has occurred (previously not banned or not found).
        
      operationId: unbanUser
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }


  /session/{userId}/unlikePhoto/{photoId}:
    delete:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: user logged
        
      - name: photoId
        schema: 
          type: integer
        in: path 
        required: true
        description: photo to be unliked

        
      
      
      tags: ["unlikePhoto"]
      summary: Given a user ID and a photo Id, the logged user unlikes it 
      description: |-
        The logged user deletes the logged user from the photo's list of users likes. 
        It returns 0 if it has been correctly unliked, or -1 if an error has occurred (previously not liked, userId or photoId not found).
        
      operationId: unlikePhoto
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }


  /session/{userId}/uncommentPhoto/{photoId}:
    delete:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: user logged
        
      - name: photoId
        schema: 
          type: integer
        in: path
        required: true
        description: ID of the photo to be uncommented

        
      
      
      tags: ["uncommentPhoto"]
      summary: Given a user ID and a photo Id, the logged user uncomments it 
      description: |-
        The logged user deletes the comment from the photo's list of comments. 
        It returns 0 if it has been correctly uncommented, or -1 if an error has occurred (previously not commented, userId or photoId not found).
        
      operationId: uncommentPhoto
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }


  /session/{userId}/deletePhoto/{photoId}:
    delete:
      parameters:
      - name: userId
        schema: 
          type: integer
        in: path
        required: true
        description: user logged
        
      - name: photoId
        schema: 
          type: integer
        in: path
        required: true
        description: ID of the photo to be deleted

        
      
      
      tags: ["deletePhoto"]
      summary: Given a user ID and a photo Id, the logged user deletes it from its stream 
      description: |-
        The logged user deletes the photo from its stream. 
        It returns 0 if it has been correctly deleted, or -1 if an error has occurred (userId or photoId not found).
        
      operationId: deletePhoto
      

      responses:
        '201': { $ref: '#/components/responses/OK' }
        '401': { $ref: "#/components/responses/Error" }



  
components:

  responses:
  
    UserInfo:
      description: Information related to the user
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
              
              
    OK: 
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/IntegerOK"
            
    Error:
      description: User ID not found or another error occurred.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/IntegerError"

              
    BadRequest:
      description: |
        The request was not compliant with the documentation
        (eg. missing fields, etc).

    InternalServerError:
      description: |
        The server encountered an internal error.
        Further info in server logs.

  schemas:
    
    
    IntegerOK:
      type: integer
      example: 1
        
    IntegerError:
      type: integer
      example: -1
    
          
    Username:
      type: string
      example: "Maria"
      readOnly: true
      minLength: 3
      maxLength: 16
    
    

      
      