openapi: 3.0.3
info:
  title: Simplified login API specification
  description: |-
    This OpenAPI document describes the simplified login API.
    Copy and paste the API from the `paths` key to your OpenAPI document.
  version: "1"


paths: 

  #-----------------------------------------
  #GET
  /session/{username}:
    parameters:
      - name: username
        schema: {$ref: "#/components/schemas/Username"}
        in: path
        required: true
        description: Username

    get: 
      summary: user searched by its username
      operationId: getUserProfile
      description: |
        Obtains an user by its username. It returns a list with the attributes of the user, or "Error" if not found.
        
      responses:
        "200":
          description: Request accepted, user found
          
          content:
            application/json:
              schema:
                type: string
                enum : 
                - users[username]
                #hay que ver las respuestas como devolverlas bien
        "400": { $ref: "#/components/responses/BadRequest" }
        "404": { description: Fountain not found}
        "500": { $ref: "#/components/responses/InternalServerError" }


  

  /session/{username}/stream:
    

    get: 
      parameters:
      - name: username
        schema: {$ref: "#/components/schemas/Username"}
        in: path
        required: true
        description: Username
      
      
      summary: Stream of photos of a user
      operationId: getMyStream
      description: |
        Obtains the stream of photos of a user searched by its username. It returns a list with all the photos in inverse chronological order
        
      responses:
        "200":
          description: Request accepted, user found
          
          content:
            application/json:
              schema:
                type: object
                enum : 
                - link
                - likes
                - (user,comment)
                - date
            #hay que ver las respuestas como devolverlas bien


        "400": { $ref: "#/components/responses/BadRequest" }
        "404": { description: Fountain not found}
        "500": { $ref: "#/components/responses/InternalServerError" }


  #-----------------------------------------
  #POST
  #Login
  /session/login:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
        
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true


      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    
                    type: integer
                    example: 1

        '401':
          description: User log-in action not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: integer
                    example: -1


  /session/{username}/uploadPhoto:
    post:
      parameters:
      - name: username
        schema: {$ref: "#/components/schemas/Username"}
        in: path
        required: true
        description: Username

    
      tags: ["uploadPhoto"]
      summary: Uploads a photo by the user
      description: |-
        Uploads a photo by the logged user and it appends to the beginning of the list
        
      operationId: uploadPhoto
      requestBody:
        description: User photo upload
        content:
          image/png:
            schema:
              type: string
              format: binary
        required: true


      responses:
        '201':
          description: User photo uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    
                    type: integer
                    example: 1

        '401':
          description: User photo upload action not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: integer
                    example: -1
  
  
  /session/{username}/commentPhoto:
    post:
      parameters:
      - name: username
        schema: {$ref: "#/components/schemas/Username"}
        in: path
        required: true
        description: Username
      
      
      tags: ["commentPhoto"]
      summary: Uploads a photo by the user
      description: |-
        Uploads a photo by the logged user and it appends to the beginning of the list
        
      operationId: commentPhoto
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true


      responses:
        '201':
          description: User photo uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    
                    type: integer
                    example: 1

        '401':
          description: User photo upload action not successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: integer
                    example: -1
  
    #-----------------------------------------
    #PUT

  #Set a new user name from an existing user
  /session/{username}/setUser:
    put:
      parameters:
        - name: username
          schema: {$ref: "#/components/schemas/Username"}
          in: path
          required: true
          description: Old username. It must exist on the database of users.

        - name: NewUsername
          schema: {$ref: "#/components/schemas/Username"}
          in: query
          required: true
          description: New username. It must be different from the old username.
      
      tags: ["setMyUserName"]
      summary: Sets new User name
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
        
      operationId: setMyUserName
      requestBody:
        description: old and new usernames
        content:
          application/json:
            schema:
              type: object
              properties:
                old_name: 
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16

                new_name:
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true


      responses:
        "200":
          description: Request accepted, username changed
          
          content:
            application/json:
              schema: {$ref: "#/components/schemas/ObjectWithInt"}
                
        "400": { $ref: "#/components/responses/BadRequest" }
        "404": { description: Fountain not found}
        "500": { $ref: "#/components/responses/InternalServerError" }


 

    

    #-----------------------------------------
    #DELETE
    
    
  
    
components:

  responses:
    BadRequest:
      description: |
        The request was not compliant with the documentation
        (eg. missing fields, etc).

    InternalServerError:
      description: |
        The server encountered an internal error.
        Further info in server logs.

  schemas:
    
    ObjectWithInt:
      type: object
      properties:
        identifier:    
          type: integer
          example: 1
          
    Username:
      type: string
      example: "Maria"
      readOnly: true
      minLength: 3
      maxLength: 16
    

