# This is the configuration file for the API service
# Description of this part is present in the `main.go` file

log:
  level: debug
#  methodname: false
#  json: false
#  destination: stderr
#  file: /tmp/debug.log
#  combinedtostdout: true
#web:
#  apihost: 127.0.0.1:3000
#  debughost: 127.0.0.1:4000
#  readtimeout: 5s
#  writetimeout: 5s
#  shutdowntimeout: 5s
#  behindproxy: false
